# Generated by Django 3.1.4 on 2024-11-27 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceries_app', '0001_initial'),
    ]

    operations = [
    ]
