# Generated by Django 3.1.4 on 2024-11-27 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceries_app', '0002_auto_20241127_1009'),
    ]

    operations = [
    ]
